# mkdocs.yml
site_name: " "

docs_dir: md  # Path to your docs directory relative to mkdocs.yml
site_dir: docs  # Output directory for the built site

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  logo: assets/favicon-192x192.png
  favicon: assets/logo.svg  
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey        # Color for headers, navigation, etc.
      accent: deep orange   # Color for links, buttons, etc.
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
            
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.snippets

nav:
  - Start: index.md
  - Vor Weihnachten:
    - Grußkarten: xmas/grusskarte.md
    - Geschenke: xmas/geschenke.md
  - Weihnachten:
    - Connections: games/connections.md
    - Harry Potter: games/harry_potter.md
    - Investments: data_analytics/investment.md
